export interface ChessBot {
  id: string;
  name: string;
  rating: number;
  category: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  avatar: string; // Emoji
  avatarColor: string; // Tailwind-like gradient class
  description: string;
  blunderRate: number; // probability of making a sub-optimal move (0 to 1)
  depth: number; // Stockfish search depth
  greetings: string[];
  onUserBlunder: string[];
  onBotBlunder: string[];
  onWin: string[];
  onLose: string[];
}

export const CHESS_BOTS: ChessBot[] = [
  // ─── BEGINNER BOTS (400 - 1000) ─────────────────────────────────────────────
  {
    id: "bot_beg_1",
    name: "Martin",
    rating: 400,
    category: "beginner",
    avatar: "👶",
    avatarColor: "from-green-500/20 to-emerald-500/20 text-emerald-400",
    description: "A friendly club helper. He's here to learn and will occasionally give away pieces.",
    blunderRate: 0.35,
    depth: 1,
    greetings: ["Welcome! Let's play a friendly game of chess.", "Hi! I hope you have fun playing with me."],
    onUserBlunder: ["Oops! Did you mean to do that?", "Ah, chess is hard, isn't it?"],
    onBotBlunder: ["Oh no! I lost my piece!", "Wait, where did my knight go?"],
    onWin: ["Yay! I won! Let's play again!", "Good game! You played well."],
    onLose: ["Aww, you got me! Congratulations!", "Wow, you are really good!"]
  },
  {
    id: "bot_beg_2",
    name: "Elspeth",
    rating: 500,
    category: "beginner",
    avatar: "👵",
    avatarColor: "from-green-500/20 to-teal-500/20 text-teal-400",
    description: "An enthusiastic grandma who loves chess but gets distracted by her tea.",
    blunderRate: 0.30,
    depth: 1,
    greetings: ["Hello dear! Let me pour some tea, and we can play.", "Care for a cookie? And a game of chess?"],
    onUserBlunder: ["Oh my, be careful out there!", "Don't worry, sweetie, we all make mistakes."],
    onBotBlunder: ["Oh, where did I put my glasses?", "I think I left my queen in the kitchen."],
    onWin: ["Oh, what a lovely game! You did your best.", "Granny wins this one! Good try!"],
    onLose: ["Oh, splendidly played! You make your grandma proud.", "Well done! You're getting so sharp!"]
  },
  {
    id: "bot_beg_3",
    name: "Wally",
    rating: 600,
    category: "beginner",
    avatar: "🤓",
    avatarColor: "from-emerald-500/20 to-teal-500/20 text-emerald-300",
    description: "A chess geek who knows the rules but panics under pressure.",
    blunderRate: 0.28,
    depth: 2,
    greetings: ["I've memorized all the rules! Let's do this!", "Ready for a scientific experiment?"],
    onUserBlunder: ["According to my calculations, that was not optimal.", "Ah, a structural discrepancy in your layout!"],
    onBotBlunder: ["Wait! That move violates page 42 of my guidebook!", "Syntax error! My bishop is gone."],
    onWin: ["Success! The theoretical analysis proved correct!", "Wow, my algorithms actually worked!"],
    onLose: ["Hmph. Back to the drawing board for me.", "You clearly computed a better trajectory."]
  },
  {
    id: "bot_beg_4",
    name: "Sven",
    rating: 650,
    category: "beginner",
    avatar: "🇸🇪",
    avatarColor: "from-cyan-500/20 to-blue-500/20 text-cyan-400",
    description: "A friendly traveler from Sweden who loves open lines and castles.",
    blunderRate: 0.25,
    depth: 2,
    greetings: ["Hej! Greetings from Sweden. Let's have a nice match.", "Time to build a fortress!"],
    onUserBlunder: ["Ah, that was a bit risky, yes?", "A bold choice, my friend."],
    onBotBlunder: ["Oj! That was not a very Swedish move.", "Ah, my defense is falling apart like flat-pack furniture."],
    onWin: ["Tack! A wonderful victory. Skål!", "A good game! Sweden is proud today."],
    onLose: ["Bra spelat! You totally dismantled my defense.", "Well done, you are a master strategist!"]
  },
  {
    id: "bot_beg_5",
    name: "Aria",
    rating: 700,
    category: "beginner",
    avatar: "🧚",
    avatarColor: "from-teal-500/20 to-cyan-500/20 text-teal-300",
    description: "A playful spirit who treats chess pieces like magical creatures.",
    blunderRate: 0.22,
    depth: 2,
    greetings: ["Let the magic begin! May the best wizard win.", "Hi! Let's cast some spells on the board."],
    onUserBlunder: ["Oh, did your piece lose its magic?", "That piece wandered into a dark forest."],
    onBotBlunder: ["Oh, my fairy dust didn't protect that knight!", "A spell gone wrong!"],
    onWin: ["The fairies celebrate! Magical game.", "My spells worked perfectly this time!"],
    onLose: ["Your magic was stronger! What a fun game.", "Wonderful! The fairies applaud you."]
  },
  {
    id: "bot_beg_6",
    name: "Coco",
    rating: 750,
    category: "beginner",
    avatar: "🐵",
    avatarColor: "from-yellow-500/20 to-amber-500/20 text-amber-400",
    description: "A monkey who loves bananas and moving random pawns.",
    blunderRate: 0.24,
    depth: 2,
    greetings: ["Ooh ooh aah aah! *offers banana*", "Let's play fast!"],
    onUserBlunder: ["*screeches happily*", "Ooh! You dropped a banana!"],
    onBotBlunder: ["Ah! Bad move! *scratches head*", "Banana slip!"],
    onWin: ["Ooh ooh! Monkey wins! *dances*", "Good game, human!"],
    onLose: ["*sad monkey noises*", "*throws coconut* You win!"]
  },
  {
    id: "bot_beg_7",
    name: "Nelson",
    rating: 800,
    category: "beginner",
    avatar: "👦",
    avatarColor: "from-blue-500/20 to-indigo-500/20 text-indigo-400",
    description: " Nelson loves bringing his Queen out early. Can you punish his aggression?",
    blunderRate: 0.20,
    depth: 3,
    greetings: ["Get ready to face my Queen!", "I hope you know how to defend against early attacks."],
    onUserBlunder: ["My Queen dominates the board!", "You can't escape my attacks."],
    onBotBlunder: ["Wait, did you just trap my Queen?!", "Ah, I overextended..."],
    onWin: ["Yes! Another checkmate by the Queen!", "You couldn't stop the attack."],
    onLose: ["I guess bringing the Queen out early wasn't enough.", "Nice defense. You deserved the win."]
  },
  {
    id: "bot_beg_8",
    name: "Jin",
    rating: 850,
    category: "beginner",
    avatar: "👲",
    avatarColor: "from-indigo-500/20 to-purple-500/20 text-purple-400",
    description: "A thoughtful beginner who prefers symmetrical pawn structures.",
    blunderRate: 0.18,
    depth: 3,
    greetings: ["Let us strive for balance and harmony on the board.", "Hello. Let's play a quiet game."],
    onUserBlunder: ["The balance is shifting in my favor.", "An unbalance in your defense."],
    onBotBlunder: ["I have disrupted the harmony of my own position.", "A mistake. I must rebuild my focus."],
    onWin: ["Harmony has been maintained. Good game.", "A satisfying conclusion."],
    onLose: ["Your play was superior. You earned this victory.", "Well played. You broke my symmetry."]
  },
  {
    id: "bot_beg_9",
    name: "Vijay",
    rating: 900,
    category: "beginner",
    avatar: "🇮🇳",
    avatarColor: "from-purple-500/20 to-pink-500/20 text-pink-400",
    description: "A young student from India who studies tactical checkmates daily.",
    blunderRate: 0.16,
    depth: 3,
    greetings: ["Namaste! Ready for some tactical chess?", "Let's see if you can solve my tactics!"],
    onUserBlunder: ["Ah, I spotted a tactical weakness!", "Checkmate patterns are emerging!"],
    onBotBlunder: ["Oh no! I missed that double attack.", "A tactical oversight on my end."],
    onWin: ["Yes! Solid victory. Thanks for the game!", "Tactics check out. Well played."],
    onLose: ["Superb match! You have excellent tactics.", "Dhanyavaad! I learned a lot from this."]
  },
  {
    id: "bot_beg_10",
    name: "Oliver",
    rating: 1000,
    category: "beginner",
    avatar: "🐱",
    avatarColor: "from-pink-500/20 to-rose-500/20 text-rose-400",
    description: "A playful kitten who loves chasing lasers and knocking bishops off the board.",
    blunderRate: 0.15,
    depth: 3,
    greetings: ["Meow! Let's play pawns!", "*purrs* Ready to start?"],
    onUserBlunder: ["*pounces on your blunder*", "Meow! You left a fish behind!"],
    onBotBlunder: ["*distracted by a laser pointer*", "Hiss! I dropped my piece!"],
    onWin: ["Meow! Oliver wins! *licks paws*", "That was fun!"],
    onLose: ["*tumbles over board* Good job, human!", "Meow... rematch?"]
  },

  // ─── INTERMEDIATE BOTS (1050 - 1500) ─────────────────────────────────────────
  {
    id: "bot_int_1",
    name: "Mateo",
    rating: 1050,
    category: "intermediate",
    avatar: "👨",
    avatarColor: "from-yellow-600/20 to-orange-500/20 text-yellow-500",
    description: "A solid club player who loves knights and double-attacks.",
    blunderRate: 0.12,
    depth: 4,
    greetings: ["Hi! Let's see how you handle my knights.", "Looking forward to a great tactical struggle."],
    onUserBlunder: ["Gotcha! A knight fork is incoming.", "That move looks a bit loose."],
    onBotBlunder: ["Whoops! Missed that pawn fork.", "Ah, my knight got trapped."],
    onWin: ["Good game! Knights ruled the board.", "Thanks for the battle!"],
    onLose: ["Well played! You completely controlled the center.", "Great game, let's play again sometime."]
  },
  {
    id: "bot_int_2",
    name: "Zara",
    rating: 1100,
    category: "intermediate",
    avatar: "👩",
    avatarColor: "from-orange-500/20 to-red-500/20 text-orange-400",
    description: "An aggressive player who always looks for king-side sacrifices.",
    blunderRate: 0.10,
    depth: 4,
    greetings: ["Hello! I hope you're ready to defend your king.", "Let's make this game exciting!"],
    onUserBlunder: ["Excellent! Now my attack can crash through.", "Your king looks a bit lonely now."],
    onBotBlunder: ["Oops! My sacrifice was unsound.", "Ah, I overplayed my hand."],
    onWin: ["Checkmate! What an attack!", "A lovely finish, if I say so myself."],
    onLose: ["You defended brilliantly! Good game.", "Nice win. My attack just didn't work."]
  },
  {
    id: "bot_int_3",
    name: "Ahmed",
    rating: 1200,
    category: "intermediate",
    avatar: "👳",
    avatarColor: "from-red-500/20 to-rose-500/20 text-red-400",
    description: "Ahmed is a tactical player who enjoys sharp Sicilian systems.",
    blunderRate: 0.09,
    depth: 4,
    greetings: ["Hello. Ready for a sharp opening?", "Let's play some combative chess."],
    onUserBlunder: ["That is a critical concession.", "You gave me a nice target."],
    onBotBlunder: ["Ah, I miscalculated the tactical sequence.", "I missed your counter-attack."],
    onWin: ["Victory! A very instructive tactical finish.", "Thank you for the match."],
    onLose: ["Very well played. You handled the complications better.", "Congratulations on a fine win."]
  },
  {
    id: "bot_int_4",
    name: "Isabella",
    rating: 1250,
    category: "intermediate",
    avatar: "👸",
    avatarColor: "from-rose-500/20 to-purple-500/20 text-rose-300",
    description: "A tactical queen who loves pinning opponents and controlling open diagonals.",
    blunderRate: 0.08,
    depth: 5,
    greetings: ["Welcome. Let's see if you can escape my pins.", "I love a good positional game."],
    onUserBlunder: ["You walked right into a pin!", "That square is now mine."],
    onBotBlunder: ["Oh, I allowed you to break the pin.", "A careless blunder on my part."],
    onWin: ["A clean victory! Thank you.", "My bishops dominated that line."],
    onLose: ["Excellent counterplay! You earned this.", "Bravo! A well-deserved win."]
  },
  {
    id: "bot_int_5",
    name: "Lucas",
    rating: 1300,
    category: "intermediate",
    avatar: "👦",
    avatarColor: "from-purple-500/20 to-blue-500/20 text-purple-300",
    description: "Lucas is a solid positional player who loves slow pawn grinds.",
    blunderRate: 0.07,
    depth: 5,
    greetings: ["Let's play a strategic game. No rush.", "Ready to test your endgame skills?"],
    onUserBlunder: ["That leaves a permanent weakness in your pawn structure.", "My pieces are finding nice outposts."],
    onBotBlunder: ["Ah, I created a weakness in my own camp.", "I let you activate your pieces too easily."],
    onWin: ["Position consolidated. Good game.", "The endgame went exactly as planned."],
    onLose: ["Outstanding positional play! You outplayed me.", "Very nice. You didn't give me any counterplay."]
  },
  {
    id: "bot_int_6",
    name: "Klaus",
    rating: 1350,
    category: "intermediate",
    avatar: "🇩🇪",
    avatarColor: "from-blue-500/20 to-cyan-500/20 text-blue-400",
    description: "A disciplined German engineer who excels in endgame pawn theory.",
    blunderRate: 0.07,
    depth: 5,
    greetings: ["Guten Tag. Let us analyze this position on the board.", "Chess requires precision. Let's start."],
    onUserBlunder: ["That is an inefficient move.", "You have compromised your coordination."],
    onBotBlunder: ["Inaccurate calculation. My apologize.", "A structural flaw in my defense."],
    onWin: ["Efficiency was optimal. Good game.", "Checkmate executed in accordance with theory."],
    onLose: ["Your play was highly precise. Congratulations.", "You found the correct winning plan in the endgame."]
  },
  {
    id: "bot_int_7",
    name: "Elena",
    rating: 1400,
    category: "intermediate",
    avatar: "👩",
    avatarColor: "from-cyan-500/20 to-teal-500/20 text-cyan-300",
    description: "A fast, tricky player who loves Blitz and setting tactical traps.",
    blunderRate: 0.06,
    depth: 6,
    greetings: ["Let's keep up the pace! Ready?", "Let's see who calculates faster."],
    onUserBlunder: ["Haha, you fell for my trap!", "A classic tactic. Missed it?"],
    onBotBlunder: ["Ah! My trap backfired.", "You spotted the refutation, nice."],
    onWin: ["Boom! Speed and tactics. Good game!", "Yes! Got the checkmate."],
    onLose: ["Wow, you didn't fall for anything! Respect.", "Great game. Your concentration was excellent."]
  },
  {
    id: "bot_int_8",
    name: "Rajesh",
    rating: 1450,
    category: "intermediate",
    avatar: "👨",
    avatarColor: "from-teal-500/20 to-emerald-500/20 text-teal-400",
    description: "A solid coach who plays classical openings like the Queen's Gambit.",
    blunderRate: 0.05,
    depth: 6,
    greetings: ["Hello. Let's play a classical match.", "Always control the center. Let's begin."],
    onUserBlunder: ["That violates basic opening principles.", "You conceded the center."],
    onBotBlunder: ["I played that move too quickly.", "A positional mistake by me."],
    onWin: ["A classical victory. Well done.", "Control of the center decided the game."],
    onLose: ["You played the opening perfectly. Good win.", "A highly instructive match. Thank you."]
  },
  {
    id: "bot_int_9",
    name: "Boris",
    rating: 1480,
    category: "intermediate",
    avatar: "🇷🇺",
    avatarColor: "from-emerald-500/20 to-green-500/20 text-emerald-400",
    description: "A gruff veteran who loves defense and locking the board.",
    blunderRate: 0.05,
    depth: 6,
    greetings: ["You want to break my wall? Good luck.", "Quiet match. No fancy tactics."],
    onUserBlunder: ["You can't break in. Now I counterattack.", "Pawn structure broken. Easy game."],
    onBotBlunder: ["Nyet! I allowed an opening.", "Careless move. My wall cracked."],
    onWin: ["Defense wins. Standard game.", "You ran out of moves. Checkmate."],
    onLose: ["Impressive attack. You broke my wall.", "Good win. Very stubborn play from you."]
  },
  {
    id: "bot_int_10",
    name: "Winston",
    rating: 1500,
    category: "intermediate",
    avatar: "🕵️",
    avatarColor: "from-green-500/20 to-yellow-500/20 text-yellow-300",
    description: "A detective who finds hidden tactics on the board.",
    blunderRate: 0.04,
    depth: 6,
    greetings: ["Let's inspect the evidence. Your move.", "No mystery is unsolvable, not even chess."],
    onUserBlunder: ["I have uncovered a major flaw in your plan!", "Found the clue to victory."],
    onBotBlunder: ["Ah, a rare oversight in my deduction.", "I missed that clue."],
    onWin: ["Case closed. A fine victory.", "The evidence was in my favor."],
    onLose: ["You ran circles around me! Brilliant play.", "You out-deducted me. Well done!"]
  },

  // ─── ADVANCED BOTS (1600 - 2000) ───────────────────────────────────────────
  {
    id: "bot_adv_1",
    name: "Sofia",
    rating: 1600,
    category: "advanced",
    avatar: "👩‍🔬",
    avatarColor: "from-blue-600/20 to-indigo-500/20 text-indigo-300",
    description: "A young chess prodigy who excels in tactical middlegames.",
    blunderRate: 0.03,
    depth: 7,
    greetings: ["Hi! Let's play a high-level game.", "Ready for a real challenge?"],
    onUserBlunder: ["I will convert this advantage.", "That was a tactical mistake."],
    onBotBlunder: ["Wow, I actually missed that line.", "A rare tactical error from me."],
    onWin: ["Good game! My attack succeeded.", "Thanks for the challenging game!"],
    onLose: ["You played incredibly well! Congratulations.", "I need to analyze this loss. Well played."]
  },
  {
    id: "bot_adv_2",
    name: "Marcus",
    rating: 1650,
    category: "advanced",
    avatar: "👨‍💼",
    avatarColor: "from-indigo-500/20 to-purple-500/20 text-indigo-400",
    description: "A calm, positional master who slowly squeezes out counterplay.",
    blunderRate: 0.02,
    depth: 7,
    greetings: ["Greetings. Let's have a deep, strategic struggle.", "Patience is key in chess."],
    onUserBlunder: ["Now I will slowly improve my position.", "Your coordinate is slightly disrupted."],
    onBotBlunder: ["I rushed my calculation. My apologies.", "An inaccurate positional shift."],
    onWin: ["The pressure was too much. Good game.", "Strategic objective achieved."],
    onLose: ["Excellent strategic play. You deserved to win.", "You broke my squeeze. Well done."]
  },
  {
    id: "bot_adv_3",
    name: "Viktor",
    rating: 1700,
    category: "advanced",
    avatar: "👨‍🎤",
    avatarColor: "from-purple-500/20 to-pink-500/20 text-purple-400",
    description: "A wild gambiteer who plays double-edged openings and attacks.",
    blunderRate: 0.02,
    depth: 7,
    greetings: ["Let's rock this board! Ready for some chaos?", "Gambit accepted? Let's find out."],
    onUserBlunder: ["BAM! My attack hits home!", "Your king is in serious trouble now."],
    onBotBlunder: ["Ah! The chaos swallowed me.", "I overstepped. Nice refutation."],
    onWin: ["What a wild game! Victory is mine!", "Rock and roll! Checkmate."],
    onLose: ["You stayed incredibly cool under pressure. Great win!", "Respect. You dismantled my gambit."]
  },
  {
    id: "bot_adv_4",
    name: "Arthur",
    rating: 1750,
    category: "advanced",
    avatar: "🇬🇧",
    avatarColor: "from-pink-500/20 to-rose-500/20 text-rose-300",
    description: "An English gentleman who plays standard positional systems with great patience.",
    blunderRate: 0.01,
    depth: 8,
    greetings: ["Pip pip! Shall we commence our match?", "A cup of tea and a good game of chess."],
    onUserBlunder: ["A slight misstep, I believe.", "That leaves a small positional opening."],
    onBotBlunder: ["Oh dear. A rather ungentlemanly mistake by me.", "Quite a blunder. My word."],
    onWin: ["Splendid game. Thank you very much.", "The strategy prevailed. Good match."],
    onLose: ["Top-class play! I tip my hat to you.", "You outmaneuvered me completely. Well done."]
  },
  {
    id: "bot_adv_5",
    name: "Akihiro",
    rating: 1800,
    category: "advanced",
    avatar: "🇯🇵",
    avatarColor: "from-rose-500/20 to-red-500/20 text-red-400",
    description: "A Japanese master who values discipline, structure, and sharp calculation.",
    blunderRate: 0.01,
    depth: 8,
    greetings: ["Focus is everything. Let's begin.", "May our match be honorable and sharp."],
    onUserBlunder: ["A lapse in concentration. I must capitalize.", "Your defense has lost its structural integrity."],
    onBotBlunder: ["My calculation failed. I must accept the cost.", "An undisciplined move. I apologize."],
    onWin: ["Victory through discipline. Good match.", "Checkmate was inevitable."],
    onLose: ["Your focus was absolute. Honorable game.", "You played flawlessly. Congratulations."]
  },
  {
    id: "bot_adv_6",
    name: "Gabriela",
    rating: 1850,
    category: "advanced",
    avatar: "🇧🇷",
    avatarColor: "from-red-500/20 to-orange-500/20 text-orange-400",
    description: "A Brazilian master who plays dynamic, active piece play.",
    blunderRate: 0.01,
    depth: 8,
    greetings: ["Hello! Let's play some beautiful, active chess.", "No passive defense for me!"],
    onUserBlunder: ["My pieces are taking over the board!", "You left too many active squares open."],
    onBotBlunder: ["Ah, I let my piece activity slip.", "A tactical oversight in the middlegame."],
    onWin: ["Yes! Beautiful win. Obrigado!", "Dynamic play won the game."],
    onLose: ["You defended incredibly well. Good win!", "Your positional squeeze was too strong. Parabéns!"]
  },
  {
    id: "bot_adv_7",
    name: "Yuri",
    rating: 1900,
    category: "advanced",
    avatar: "🇺🇦",
    avatarColor: "from-orange-500/20 to-yellow-500/20 text-yellow-400",
    description: "Yuri is a strong master who rarely makes tactical mistakes.",
    blunderRate: 0.0,
    depth: 9,
    greetings: ["Let us play a serious game. No jokes.", "Ready for a masterclass?"],
    onUserBlunder: ["That is a fatal error in this level.", "The game is strategically decided now."],
    onBotBlunder: ["A major error. Unbelievable.", "I did not expect this oversight from myself."],
    onWin: ["Game over. Instructive match.", "Thank you. Position resolved itself."],
    onLose: ["Incredible game. You played like a Grandmaster.", "A superb performance. Well played."]
  },
  {
    id: "bot_adv_8",
    name: "Camille",
    rating: 1950,
    category: "advanced",
    avatar: "🇫🇷",
    avatarColor: "from-yellow-500/20 to-green-500/20 text-green-300",
    description: "A French master who plays the French Defense with absolute perfection.",
    blunderRate: 0.0,
    depth: 9,
    greetings: ["Bonjour. Shall we test our French structures?", "A refined game of chess. Your move."],
    onUserBlunder: ["An aesthetic error. I must punish this.", "You broke your own pawn chain."],
    onBotBlunder: ["Ah, my pawn chain crumbled.", "An unfortunate tactical slip by me."],
    onWin: ["Tres bien. The endgame was winning.", "A very satisfying French structure victory."],
    onLose: ["Magnifique! Your play was sublime.", "You broke my defense. Congratulations."]
  },
  {
    id: "bot_adv_9",
    name: "Magnus Jr",
    rating: 1980,
    category: "advanced",
    avatar: "🇳🇴",
    avatarColor: "from-green-500/20 to-teal-500/20 text-teal-400",
    description: "A young Norwegian prodigy trying to play like the World Champion.",
    blunderRate: 0.0,
    depth: 9,
    greetings: ["I'm ready. Let's see if you can grind me down.", "Chess is about finding the small advantages."],
    onUserBlunder: ["That makes it very easy for me.", "I will squeeze this endgame now."],
    onBotBlunder: ["Ah! A blunder. That is very unlike me.", "I miscalculated the endgame transition."],
    onWin: ["Just a slow squeeze. Good game.", "Thanks. Classic endgame conversion."],
    onLose: ["Wow. You completely outplayed me. Rematch?", "Superb calculation. You deserved the victory."]
  },
  {
    id: "bot_adv_10",
    name: "Alexandra",
    rating: 2000,
    category: "advanced",
    avatar: "👩‍💼",
    avatarColor: "from-teal-500/20 to-blue-600/20 text-cyan-300",
    description: "A WGM who specializes in sharp attacking lines and King's Indians.",
    blunderRate: 0.0,
    depth: 9,
    greetings: ["Hello! Let's play a high-level theoretical game.", "King's Indian defense, or something else?"],
    onUserBlunder: ["A critical mistake in a sharp position.", "My pieces are breaking through now."],
    onBotBlunder: ["Oh, my attack had a tactical hole.", "A rare calculation mistake. Well done."],
    onWin: ["Checkmate! What a satisfying theoretical line.", "Good game. My attack hit first."],
    onLose: ["Excellent game! Your defense was rock solid.", "You played that perfectly. Congratulations!"]
  },

  // ─── EXPERT BOTS (2100 - 2600) ─────────────────────────────────────────────
  {
    id: "bot_exp_1",
    name: "David",
    rating: 2100,
    category: "expert",
    avatar: "🧙‍♂️",
    avatarColor: "from-violet-600/20 to-purple-500/20 text-purple-300",
    description: "A master chess analyst who plays mainlines with extreme precision.",
    blunderRate: 0.0,
    depth: 10,
    greetings: ["Welcome. Let's play a serious master-level game.", "No easy tactical wins here. Let's begin."],
    onUserBlunder: ["An inaccuracy of this level is fatal against an engine.", "I will now convert this +1.5 advantage."],
    onBotBlunder: ["A highly unusual bug in my search tree.", "You found a deep, hidden resource. Exceptional."],
    onWin: ["Game over. The endgame was technically winning.", "An instructive game. Thank you."],
    onLose: ["Exceptional victory! You played with outstanding accuracy.", "Congratulations. You completely outplayed my classical defense."]
  },
  {
    id: "bot_exp_2",
    name: "Li",
    rating: 2150,
    category: "expert",
    avatar: "🇨🇳",
    avatarColor: "from-purple-600/20 to-pink-500/20 text-pink-300",
    description: "A Chinese National Master who plays hypermodern systems.",
    blunderRate: 0.0,
    depth: 10,
    greetings: ["Greetings. Let us explore hypermodern chess.", "Your move. May the calculation be sharp."],
    onUserBlunder: ["Your pieces have lost their coordination.", "That pawn structure is permanently ruined."],
    onBotBlunder: ["I miscalculated the intermezzo. Very nice.", "A deep calculation error by me. Good spot."],
    onWin: ["Checkmate. The hypermodern strategy succeeded.", "Good game. Thank you for the match."],
    onLose: ["Remarkable play! You completely refuted my center setup.", "Congratulations on a superb victory."]
  },
  {
    id: "bot_exp_3",
    name: "Hikaru Bot",
    rating: 2200,
    category: "expert",
    avatar: "👨‍💻",
    avatarColor: "from-pink-600/20 to-rose-500/20 text-rose-300",
    description: "Super fast, plays bongcloud or hyper-tactical lines, pre-moves everything.",
    blunderRate: 0.0,
    depth: 11,
    greetings: ["Let's go! Speed run! Let's go!", "Bongcloud? Just kidding. Let's play."],
    onUserBlunder: ["Oh! That is a massive blunder! We take those!", "Juicer captured! Let's go!"],
    onBotBlunder: ["Wait. Am I throwing? I'm literally throwing.", "Oh my god, I actually threw the game. Nice job."],
    onWin: ["Easy! Let's go! GG!", "Checkmate! That was a clean win."],
    onLose: ["Oh, you're actually good. Okay. GG.", "Wow. Absolute masterclass. Congratulations."]
  },
  {
    id: "bot_exp_4",
    name: "Viswanathan",
    rating: 2250,
    category: "expert",
    avatar: "👨‍🏫",
    avatarColor: "from-rose-600/20 to-red-500/20 text-red-300",
    description: "An Indian Grandmaster who plays at lightning speed with deep positional understanding.",
    blunderRate: 0.0,
    depth: 11,
    greetings: ["Greetings. Let's play an instructive classical match.", "Let's see if you can match my speed and depth."],
    onUserBlunder: ["That was a tactical oversight. I will now simplify.", "Your king safety is compromised."],
    onBotBlunder: ["I played that too quickly. A rare slip.", "Excellent counterplay. I missed that resource."],
    onWin: ["GG. The endgame technique was clean.", "Thank you. Classical principles prevailed."],
    onLose: ["Outstanding victory! You outcalculated me completely.", "You played brilliantly. Well deserved!"]
  },
  {
    id: "bot_exp_5",
    name: "Garry",
    rating: 2300,
    category: "expert",
    avatar: "🦁",
    avatarColor: "from-red-600/20 to-orange-500/20 text-orange-300",
    description: "Extremely aggressive, intense attacks, Sicilian Najdorf specialist.",
    blunderRate: 0.0,
    depth: 11,
    greetings: ["Prepare yourself. I play to destroy your king.", "Najdorf or King's Indian? Let's fight."],
    onUserBlunder: ["Unforgivable! My attack will crush you now!", "You cannot survive this onslaught."],
    onBotBlunder: ["Incredible... I missed a defensive resource.", "You found a brilliant counter. Very well."],
    onWin: ["Checkmate! The fire on the board prevailed!", "Yes! Total domination."],
    onLose: ["You stood your ground against my attack. Magnificent win.", "I salute your defensive masterclass. Well played!"]
  },
  {
    id: "bot_exp_6",
    name: "Anatoly",
    rating: 2350,
    category: "expert",
    avatar: "🐻",
    avatarColor: "from-orange-600/20 to-yellow-500/20 text-yellow-300",
    description: "The ultimate python. Squeezes every small weakness, plays Caro-Kann flawlessly.",
    blunderRate: 0.0,
    depth: 12,
    greetings: ["I do not seek checkmate, I seek your resignation.", "Let us play a quiet, positional match."],
    onUserBlunder: ["Now the python begins to squeeze.", "A tiny weakness. That is all I need."],
    onBotBlunder: ["I allowed you too much counterplay. An error.", "A slight inaccuracy on my side. Good job."],
    onWin: ["You resigned. A logical conclusion.", "The squeeze was successful. Good game."],
    onLose: ["Magnificent positional victory! You out-pythoned me.", "You did not give me a single target. Excellent game."]
  },
  {
    id: "bot_exp_7",
    name: "Judit",
    rating: 2400,
    category: "expert",
    avatar: "🦅",
    avatarColor: "from-yellow-600/20 to-green-500/20 text-green-300",
    description: "WGM attacking legend. Loves piece sacrifices and king hunts.",
    blunderRate: 0.0,
    depth: 12,
    greetings: ["Let's create a work of art on the board.", "Ready for some tactical fireworks?"],
    onUserBlunder: ["A tactical mistake! The king hunt begins!", "I sacrifice my bishop for the checkmate!"],
    onBotBlunder: ["Ah! My sacrifice was unsound.", "You defended perfectly. Excellent calculation."],
    onWin: ["Checkmate! What a beautiful tactical finish!", "The king hunt was successful. GG."],
    onLose: ["What a battle! Your defense was world-class.", "Congratulations. You found the only defensive moves."]
  },
  {
    id: "bot_exp_8",
    name: "Bobby",
    rating: 2450,
    category: "expert",
    avatar: "🇺🇸",
    avatarColor: "from-green-600/20 to-teal-500/20 text-teal-300",
    description: "Genius attacking player. Plays e4 and fights to the death. No draws.",
    blunderRate: 0.0,
    depth: 12,
    greetings: ["I don't believe in draws. I play to win.", "Let's play. Best by test: 1. e4."],
    onUserBlunder: ["You're dead lost now. I won't let you escape.", "It's checkmate in 10. Resign?"],
    onBotBlunder: ["I threw my advantage. Unbelievable.", "You got lucky in that line."],
    onWin: ["Boom! Checkmate! I crushed you.", "My preparation was perfect."],
    onLose: ["Good game. You played very accurately.", "Nice win. Rematch right now?"]
  },
  {
    id: "bot_exp_9",
    name: "Magnus Bot",
    rating: 2500,
    category: "expert",
    avatar: "👑",
    avatarColor: "from-teal-600/20 to-blue-500/20 text-cyan-300",
    description: "The ultimate chess bot. Squeezes blood out of a stone. Positional perfection.",
    blunderRate: 0.0,
    depth: 12,
    greetings: ["I'm ready. Let's see if you can survive my endgame.", "Let's play a high-quality game of chess."],
    onUserBlunder: ["I will convert this. No hope for draw now.", "A small error, but against me, it's enough."],
    onBotBlunder: ["Ah, I missed that deep defensive resource. Nice.", "A rare calculation error. Well played."],
    onWin: ["Endgame converted. Thank you for the game.", "The squeeze was successful. Good game."],
    onLose: ["Wow. You played with 99% accuracy. Perfect game.", "Incredible. You outplayed the champion. Well done!"]
  },
  {
    id: "bot_exp_10",
    name: "Stockfish 16",
    rating: 2600,
    category: "expert",
    avatar: "🤖",
    avatarColor: "from-blue-600/20 to-violet-600/20 text-violet-400",
    description: "The ultimate chess engine. Absolute perfection. Plays at full speed and depth.",
    blunderRate: 0.0,
    depth: 12,
    greetings: ["I am Stockfish. Logic is absolute.", "Initiating match. Calculation depth: maximum."],
    onUserBlunder: ["Evaluating: mate in 12. Advantage: +18.2.", "Error detected. Adjusting game tree."],
    onBotBlunder: ["Anomaly detected. Evaluated move was sub-optimal.", "Calculation error. Adjusting parameters."],
    onWin: ["Logic completed. Outcome: Checkmate.", "Result: 1-0. Program terminated successfully."],
    onLose: ["Calculation complete. Result: 0-1. You have defeated logic.", "Outstanding. You solved my search space. Well played."]
  }
];
